#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  build_dispatcher_list.sh --mode old|both|new --old SIP_URI --new SIP_URI --output FILE [--set-id N]

Examples:
  build_dispatcher_list.sh --mode old  --old sip:198.51.100.10:5060 --new sip:198.51.100.20:5060 --output ./dispatcher.profile.old.list
  build_dispatcher_list.sh --mode both --old sip:198.51.100.10:5060 --new sip:198.51.100.20:5060 --output ./dispatcher.profile.both.list
  build_dispatcher_list.sh --mode new  --old sip:198.51.100.10:5060 --new sip:198.51.100.20:5060 --output ./dispatcher.profile.new.list
USAGE
}

MODE=""
OLD_URI=""
NEW_URI=""
OUTPUT=""
SET_ID="1"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="${2:-}"; shift 2 ;;
    --old) OLD_URI="${2:-}"; shift 2 ;;
    --new) NEW_URI="${2:-}"; shift 2 ;;
    --output) OUTPUT="${2:-}"; shift 2 ;;
    --set-id) SET_ID="${2:-}"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "$MODE" || -z "$OLD_URI" || -z "$NEW_URI" || -z "$OUTPUT" ]]; then
  usage
  exit 1
fi

if [[ "$MODE" != "old" && "$MODE" != "both" && "$MODE" != "new" ]]; then
  echo "--mode must be one of: old, both, new" >&2
  exit 1
fi

if [[ "$OLD_URI" != sip:* && "$OLD_URI" != sips:* ]]; then
  echo "--old must be SIP URI (sip:... or sips:...)" >&2
  exit 1
fi

if [[ "$NEW_URI" != sip:* && "$NEW_URI" != sips:* ]]; then
  echo "--new must be SIP URI (sip:... or sips:...)" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

{
  echo "# Generated by build_dispatcher_list.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "# Mode: ${MODE}"
  echo "# Format: setid destination flags priority attrs"
  case "$MODE" in
    old)
      echo "${SET_ID} ${OLD_URI} 0 0 old-pbx"
      ;;
    both)
      echo "${SET_ID} ${OLD_URI} 0 0 old-pbx"
      echo "${SET_ID} ${NEW_URI} 0 0 new-pbx"
      ;;
    new)
      echo "${SET_ID} ${NEW_URI} 0 0 new-pbx"
      ;;
  esac
} > "$OUTPUT"

echo "Dispatcher profile written: $OUTPUT"
